### PR TITLE
Fix several additional typos

### PR DESCRIPTION
**Pull request by tombuzbee**
The Project Gutenberg text had several corrections in March of 2017.
After noticing a couple myself, I diffed the PG revisions to find the rest.

### CODE REVIEW

**Comment by acabal** [comment]
Thanks! One minor tweak, can you please remove the dash from `shop-window` as this is scripted spelling modernization. Once that's taken care of I can merge the rest in.

How difficult was it to diff against the PG source? Do you think that's something that can be scripted to some reasonable extent?

**Comment by tombuzbee** [comment]
Done.

The revisions in question had a lot of formatting noise like changing straight quotes to curly quotes. It would probably be possible to do with some kind of preprocessing step to ignore these sorts of changes, but then I think it would still need manual review. Other than that it wasn't really difficult.

**Comment by tombuzbee** [comment]
Oh, and to clarify: I diffed two PG revisions against each other. Not SE vs. PG

**Comment by acabal** [comment]
Sorry I was unclear, the word is `shopwindow` without a space, just as it was in SE source.

**Comment by tombuzbee** [comment]
Hmm, that looks wrong to me and my spellchecker flags it as an error, but I'll change it back.

**Comment by acabal** [comment]
Thanks! https://www.merriam-webster.com/dictionary/shopwindow

**Pull request merged**
